[package]
name = "zed-wing"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/wing.rs"
crate-type = ["cdylib"]

[dependencies]
serde = { version = "1.0.204", features = ["derive"] }
zed_extension_api = "0.0.6"
