name = "wing"
grammar = "wing"
path_suffixes = ["w"]
line_comments = ["// "]
autoclose_before = ")}]"
brackets = [
  { start = "(", end = ")", close = true, newline = true },
  { start = "{", end = "}", close = true, newline = true },
  { start = "[", end = "]", close = true, newline = true },
  { start = "\"", end = "\"", close = true, newline = false },
]
hard_tabs = true
